### ISSUE TITLE
violation of the dependency-less claim

### ISSUE THREAD

**Issue by McTrk** [boppreh/hello_tls#2]
https://github.com/boppreh/hello_tls/blame/ac3d6070f445a7e91d9f558468441fcfc395600b/src/hello_tls/scan.py#L166

```
$ pwd
/home/user/git/github/hello_tls/src
[user@host src]$ python
Python 3.9.18 (main, Sep  7 2023, 00:00:00) 
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hello_tls
>>> c=hello_tls.ConnectionSettings("boppreh.com", 443)
>>> r=hello_tls.scan_server(c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usergit/github/hello_tls/src/hello_tls/scan.py", line 326, in scan_server
    for i, _ in enumerate(pool.imap_unordered(lambda t: t(), tasks)):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/git/github/hello_tls/src/hello_tls/scan.py", line 326, in <lambda>
    for i, _ in enumerate(pool.imap_unordered(lambda t: t(), tasks)):
  File "/home/user/git/github/hello_tls/src/hello_tls/scan.py", line 320, in <lambda>
    tasks.append(lambda: tmp_certificate_chain.extend(get_server_certificate_chain(connection_settings, client_hello)))
  File "/home/user/git/github/hello_tls/src/hello_tls/scan.py", line 166, in get_server_certificate_chain
    from OpenSSL import SSL, crypto
ModuleNotFoundError: No module named 'OpenSSL'
>>> 
```

**Comment by boppreh** [comment]
https://github.com/boppreh/hello_tls/blob/ac3d6070f445a7e91d9f558468441fcfc395600b/README.md#L7

> Optionally, the certificate chain can be fetched and parsed, at the cost of relying on pyOpenSSL.

Please use [`--no-certs`](https://github.com/boppreh/hello_tls/blob/ac3d6070f445a7e91d9f558468441fcfc395600b/src/hello_tls/__main__.py#L15C18-L15C18) or [`scan_server(..., fetch_cert_chain=False)`](https://github.com/boppreh/hello_tls/blob/ac3d6070f445a7e91d9f558468441fcfc395600b/src/hello_tls/scan.py#L271C5-L271C21) to disable this. You won't get a certificate chain, but all the other scans will be there.

And thanks for the reminder, there are other things I want to update from the README.
